### ISSUE TITLE
Make it clear that we've shuttered this tool and merged its capabilities into VictiScout

### ISSUE THREAD

**Issue by ErikBoesen** [ErikBoesen/vs#5]
We should add an explanation of this to the README, etc.

**Comment by ErikBoesen** [comment]
@AndrewLester @JosephCarpenter One of you do this, it should be pretty easy

**Comment by flyawayfpv** [comment]
accomplished?


-Evan

**Comment by ErikBoesen** [comment]
@ecbcat20 Uh, no, not accomplished.

**Comment by ErikBoesen** [comment]
Fixed with #6. Going to transfer this to my own account now.
